name: Test Build Configurations

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        date-ranges: [{arg: "2022-11-01 2022-12-31", suffix: "2022-nov-dec"}]
        personal-goals: [{arg: "--personal-goals", suffix: ""}, {arg: "--no-personal-goals", suffix: "-no-personal-goals"}]
        work-goals: [{arg: "--work-goals", suffix: ""}, {arg: "--no-work-goals", suffix: "-no-work-goals"}]
        daily-pages: [{arg: "--daily-pages", suffix: ""}, {arg: "--no-daily-pages", suffix: "-no-daily"}]
        weekly-pages: [{arg: "--weekly-pages", suffix: ""}, {arg: "--no-weekly-pages", suffix: "-no-weekly"}]
        journal-pages: 
          - {arg: "--journals-per-page=0", suffix: ""}
          - {arg: "--journals-per-page=2", suffix: "-half-pg-journal"}
          - {arg: "--journals-per-page=4", suffix: "-quarter-pg-journal"}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node packages
        run: npm install
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true 
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: yes | pip install Jinja2 playwright python-dateutil
      - name: Install playwright browsers
        run: playwright install
      - name: Build planner pages 
        run: npm run build -- ${{ matrix.date-ranges.arg }} ${{ matrix.personal-goals.arg }} ${{ matrix.work-goals.arg }} ${{ matrix.daily-pages.arg }} ${{ matrix.weekly-pages.arg }} --file-suffix="-${{ matrix.date-ranges.suffix }}${{ matrix.daily-pages.suffix }}${{ matrix.weekly-pages.suffix }}${{ matrix.personal-goals.suffix }}${{ matrix.work-goals.suffix }}"
      - name: Upload planner pdf to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: planner-${{ matrix.date-ranges.suffix }}${{ matrix.daily-pages.suffix }}${{ matrix.weekly-pages.suffix }}${{ matrix.personal-goals.suffix }}${{ matrix.work-goals.suffix }}.pdf
          path: dest/planner-${{ matrix.date-ranges.suffix }}${{ matrix.daily-pages.suffix }}${{ matrix.weekly-pages.suffix }}${{ matrix.personal-goals.suffix }}${{ matrix.work-goals.suffix }}.pdf
